name: Go
on: [push]
jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.7'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get go toolchains
      run: |
        go get -u golang.org/x/tools/cmd/goimports
        go get -u golang.org/x/lint/golint
        sudo cp $GOPATH/bin/goimports /usr/bin/
        sudo cp $GOPATH/bin/golint /usr/bin/
      env:
        GOPATH: /home/runner/work/gonstructor/go

    - name: Do test
      run: make check
      env:
        GOPATH: /home/runner/work/gonstructor/go

